### ISSUE TITLE
add a "shell" option

### ISSUE THREAD

**Issue by Neo-Desktop** [threeal/cmake-action#57]
Hi there,

I'd like to use the cmake-action script but have it run in a "custom shell"
(i.e. having it run in an alpine chroot provided by `jirutka/setup-alpine@v1`)

specifying a `shell` option on a `run` build step allows us to use the chroot

is it possible to add that same functionality to the cmake action?

**Comment by threeal** [comment]
Sure thing! I'll work on adding that feature for you right away. You can expect it to be included in the upcoming v1.3.0 release. Stay tuned!

**Comment by threeal** [comment]
All set, @Neo-Desktop!

Just hang tight until the next release on #55. Meanwhile, you can make use of the new feature in this action by specifying a specific tag (e.g., `threeal/cmake-action@7ef2eb8`).
