### ISSUE TITLE
Better documentation for output `build-dir`

### ISSUE THREAD

**Issue by Jim-Bar** [threeal/cmake-action#60]
Hi,

First of all thanks for this action.

I am trying to use the [`build-dir` output value](https://github.com/marketplace/actions/cmake-action#outputs) but I am not sure how to read it. I have tried the following:

    - name: Build the project
      id: build-project
      uses: threeal/cmake-action@v1.2.0
      with:
        run-build: true
        source-dir: engine
    - name: Upload built artifact
      uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: ${{ steps.build-project.outputs.build-dir }}/my-artifact

But the output is empty (it ends up being `/my-artifact`). A working example [here](https://github.com/marketplace/actions/cmake-action#examples) would be welcome.

**Comment by threeal** [comment]
Hey there, my bad! Just a heads up, the `build-dir` output value isn't up and running in [`v1.2.0`](https://github.com/threeal/cmake-action/releases/tag/v1.2.0) yet. But no worries, it's all set to roll in the upcoming v1.3.0 release (#55). In the meantime, if you're itching to try it out, you can use the `@main` or `@7ef2eb8` to try that feature.

**Comment by Jim-Bar** [comment]
Thanks for your answer, for now I'll just hardcode the path and wait for v1.3.0 to test that out.

**Comment by threeal** [comment]
Just a quick update @Jim-Bar, I've just rolled out [v1.3.0](https://github.com/threeal/cmake-action/releases/tag/v1.3.0). Feel free to dive right in and start using it!

**Comment by Jim-Bar** [comment]
It works as expected now, thanks!
