### ISSUE TITLE
Buildbot unable to find LLVM package with cmake

### ISSUE THREAD

**Issue by shraiysh** [threeal/cmake-action#67]
Hi folks, I am trying to use this action in conjunction with KyleMayes/install-llvm-action@v1, but `cmake` is not able to find the LLVM package. `cmake` is also using the clang 14.0 compiler instead of the clang-17 compiler that was just installed. The action for reference is here - https://github.com/shraiysh/temp/actions/runs/6605078058/job/17939899398

Any help finding the right package, and/or finding the right clang compiler will be appreciated. Thanks!

**Comment by threeal** [comment]
Try adding another option to set `

**Comment by shraiysh** [comment]
I tried doing that - 

- Setting it to the path where `FindLLVM.Config` exists - `CMAKE_MODULE_PATH=/home/runner/work/temp/temp/llvm/lib/cmake/llvm/` ([link to job](https://github.com/shraiysh/temp/actions/runs/6613362929/job/17961051661))
- Setting it to the installation directory - `CMAKE_MODULE_PATH=/home/runner/work/temp/temp/llvm/` ([link to job](https://github.com/shraiysh/temp/actions/runs/6613397533/job/17961159577))

Both of these are still not able to find the package. Plus, this doesn't help with the fact that the CXX and C compilers being used are Clang 14.0.0. 
![image](https://github.com/threeal/cmake-action/assets/38454954/8e860ece-aac0-4bc2-ab6f-9fba5b985a19)

**Comment by threeal** [comment]
If you want to set the compilers too, you can provide the full compiler path to the `CMAKE_C_COMPILER` and `CMAKE_CXX_COMPILER` options. In this action case, you can provide that from the `c-compiler` and `cxx-compiler` inputs.

**Comment by shraiysh** [comment]
I understand that if I provide the full path, it will identify the compiler, but that shouldn't be required, because they are already in `PATH`. If you look at 3rd step of the job (clang version) - the command `clang --version` shows the 17.0.2 compiler, but for some reason cmake is not able to pick that up. I am also concerned that because it cannot see the binaries, it might also not be able to see the libraries installed by the action (which should again be in the `LIBRARY_PATH` and `LD_LIBRARY_PATH` variables.

I will still try with full path to clang-17 and see if that succeeds.

**Comment by threeal** [comment]
Aaah i see..

Hmm.. i also not really sure how CMake detect the compiler, it should automatically detect the 17.0.2 compiler if it's already in the path. But anyway, does it detect `clang++` command? is it on 17.0.2 too?

**Comment by shraiysh** [comment]
`clang++ --version` also points to the 17.0.2. With the full path given by `which clang` and `which clang++`, the cmake command fails to even find those compilers. [Job link](https://github.com/shraiysh/temp/actions/runs/6614425169/job/17964373001).

**Comment by shraiysh** [comment]
Ah.. I found the issue - the checkout repository step was scheduled after installing llvm. As part of the checkout step, we were deleting the folder where llvm was installed. Reordering these steps ran the job successfully. cmake not finding the full path to compiler hinted me to see if it is getting deleted. Thank you for nudging me in that direction. I will close this issue now.
